# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather App Project 5 Atheer Alzahrani' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather App Project 5 Atheer Alzahrani
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'NVActivityIndicatorView'
end
